default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v1.17.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      # Run the linter.
      - id: ruff
        stages: [pre-commit]
      # Run the formatter.
      - id: ruff-format
        stages: [pre-commit]
