FROM python:3.14-alpine@sha256:f6a589d43c42b9e7f7dc67a12d37132491f362859a5d750607710cc56da3bc72 AS builder

COPY --from=ghcr.io/astral-sh/uv:0.12.23@sha256:61d393e44e249f2e4b526b6c7ddcecce245946826e608e11c93ad4f5bba55b21 /uv /uvx /bin/

# Change the working directory to the `app` directory
WORKDIR /app

# Install dependencies in a cache layer. This speeds up build time
RUN --mount=type=cache,target=/root/.cache/uv \
  --mount=type=secret,id=nexus_username \
  --mount=type=secret,id=nexus_password \
  --mount=type=bind,source=uv.lock,target=uv.lock \
  --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
  UV_INDEX_NEXUS_USERNAME="$(cat /run/secrets/nexus_username)" \
  UV_INDEX_NEXUS_PASSWORD="$(cat /run/secrets/nexus_password)" \
  uv sync --locked --no-install-project --no-editable

# Copy the project into the intermediate image
COPY . /app

# Sync the project and install it, now that we have access to the source code
RUN --mount=type=cache,target=/root/.cache/uv \
  --mount=type=secret,id=nexus_username \
  --mount=type=secret,id=nexus_password \
  UV_INDEX_NEXUS_USERNAME="$(cat /run/secrets/nexus_username)" \
  UV_INDEX_NEXUS_PASSWORD="$(cat /run/secrets/nexus_password)" \
  uv sync --locked --no-editable --no-dev

FROM python:3.14-alpine@sha256:f6a589d43c42b9e7f7dc67a12d37132491f362859a5d750607710cc56da3bc72

# Create a non-root user and group with specific IDs
RUN addgroup -S -g 1000 app && adduser -S -u 1000 -G app app

# Copy the environment, but not the source code
COPY --from=builder --chown=app:app /app/.venv /app/.venv

# Switch to the non-root user
USER app

# Expose the correct port
EXPOSE 8001

# Run the application
CMD ["/app/.venv/bin/home-dashboard-api"]
