FROM python:3.14-alpine@sha256:016508ba505da24f7139765bc4bb669df4e88eb2f12eeadd571bf2f88d7533df AS builder
COPY --from=ghcr.io/astral-sh/uv:0.12.15@sha256:62f8c047d0a0e9ece6b53fc63df902585a67a47a7f318ddec4a37db586edc8e3 /uv /uvx /bin/


# Change the working directory to the `app` directory
WORKDIR /app

# Install dependencies in a cache layer. This speeds up build time
RUN --mount=type=cache,target=/root/.cache/uv \
  --mount=type=secret,id=nexus_username \
  --mount=type=secret,id=nexus_password \
  --mount=type=bind,source=uv.lock,target=uv.lock \
  --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
  UV_INDEX_NEXUS_USERNAME="$(cat /run/secrets/nexus_username)" \
  UV_INDEX_NEXUS_PASSWORD="$(cat /run/secrets/nexus_password)" \
  uv sync --locked --no-install-project --no-editable

# Copy the project into the intermediate image
COPY . /app

# Sync the project and install it, now that we have access to the source code
RUN --mount=type=cache,target=/root/.cache/uv \
  --mount=type=secret,id=nexus_username \
  --mount=type=secret,id=nexus_password \
  UV_INDEX_NEXUS_USERNAME="$(cat /run/secrets/nexus_username)" \
  UV_INDEX_NEXUS_PASSWORD="$(cat /run/secrets/nexus_password)" \
  uv sync --locked --no-editable --no-dev

FROM python:3.14-alpine@sha256:016508ba505da24f7139765bc4bb669df4e88eb2f12eeadd571bf2f88d7533df

# Create a non-root user and group with specific IDs
RUN addgroup -S -g 1000 app && adduser -S -u 1000 -G app app

# Copy the environment from builder
COPY --from=builder --chown=app:app /app/.venv /app/.venv

# Switch to the non-root user
USER app

# Expose the correct port
EXPOSE 8080

# Run the application using the compiled app command
CMD ["/app/.venv/bin/home-dashboard-web"]
