name: Build and Push Docker Images
on:
  push:
    tags:
      - "backend*"
      - "frontend*"
env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: ${{ github.repository_owner }}/home-dashboard-api
  FRONTEND_IMAGE_NAME: ${{ github.repository_owner }}/home-dashboard-web
jobs:
  build-and-push-backend:
    name: Build and Push Backend
    runs-on: homelab-runners
    # Only run for backend tags
    if: contains(github.ref, 'backend')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Log in to the Container registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: tag
        run: echo "TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ./src/backend
          file: ./src/backend/Dockerfile.secured
          push: true
          secrets: |
            nexus_username=${{ secrets.NEXUS_USERNAME }}
            nexus_password=${{ secrets.NEXUS_PASSWORD }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ steps.tag.outputs.TAG }}
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest
    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
      app: backend
  build-and-push-frontend:
    name: Build and Push Frontend
    runs-on: homelab-runners
    # Only run for frontend tags
    if: contains(github.ref, 'frontend')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Log in to the Container registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: tag
        run: echo "TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ./src/frontend
          file: ./src/frontend/Dockerfile.secured
          push: true
          secrets: |
            nexus_username=${{ secrets.NEXUS_USERNAME }}
            nexus_password=${{ secrets.NEXUS_PASSWORD }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ steps.tag.outputs.TAG }}
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
      app: frontend
